[package]
name = "ray"
version = "0.1.0"
authors = ["RickyBoyd <richard@fluidstack.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
piston_window = "0.105.0"
image = "*"
nalgebra-glm = "0.3"